# Generated by Django 3.1.5 on 2021-03-31 14:14

from django.db import migrations, models
import django_shop.account.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210120_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, unique=True, validators=[django_shop.account.models.validate_phone], verbose_name='شماره موبایل'),
        ),
    ]
